# Bot-specific gem requirements
group :scorekeeper do
  gem 'chronic'
end

# Additions to the DataMapper requirements
group :datamapper do
  gem 'dm-ar-finders'
  gem 'dm-validations'
  gem 'dm-timestamps'
end
