#!/usr/bin/env ruby
#
# Controller for the Autumn daemon. Starts, stops, and manages the daemon. Must
# be run from the Autumn root directory.
# 
#  Usage: script/daemon <command> <options> -- <application options>
#  
#  * where <command> is one of:
#    start         start an instance of the application
#    stop          stop all instances of the application
#    restart       stop all instances and restart them afterwards
#    run           start the application and stay on top
#    zap           set the application to a stopped state
#  
#  * and where <options> may contain several of the following:
#  
#      -t, --ontop                      Stay on top (does not daemonize)
#      -f, --force                      Force operation
#  
#  Common options:
#      -h, --help                       Show this message
#          --version                    Show version

require 'rubygems'
require 'daemons'

root = File.expand_path("#{File.dirname(__FILE__)}/..")

Daemons.run "#{root}/script/server", :app_name => 'autumn', :dir_mode => :normal, :dir => "#{root}/tmp", :multiple => false, :backtrace => true, :monitor => false, :log_output => true
