#!/usr/bin/env ruby
#
# Runs Autumn from the command line. This script will not exit until all leaves
# have exited. To use this script as a daemon, see the script/daemon script.

require 'libs/autumn'
$: << Autumn::Config.root
require 'libs/genesis'

puts "Loading Autumn #{Autumn::Config.version}"
Autumn::Genesis.new.boot!
